# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/giniunaite/clion-2017.3.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/giniunaite/clion-2017.3.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/giniunaite/NC-non-uniform

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/giniunaite/NC-non-uniform

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/giniunaite/clion-2017.3.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/giniunaite/clion-2017.3.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giniunaite/NC-non-uniform/CMakeFiles /home/giniunaite/NC-non-uniform/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/giniunaite/NC-non-uniform/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named analytical_piecewise_constant_end

# Build rule for target.
analytical_piecewise_constant_end: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 analytical_piecewise_constant_end
.PHONY : analytical_piecewise_constant_end

# fast build rule for target.
analytical_piecewise_constant_end/fast:
	$(MAKE) -f CMakeFiles/analytical_piecewise_constant_end.dir/build.make CMakeFiles/analytical_piecewise_constant_end.dir/build
.PHONY : analytical_piecewise_constant_end/fast

#=============================================================================
# Target rules for targets named analytical_piecewise

# Build rule for target.
analytical_piecewise: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 analytical_piecewise
.PHONY : analytical_piecewise

# fast build rule for target.
analytical_piecewise/fast:
	$(MAKE) -f CMakeFiles/analytical_piecewise.dir/build.make CMakeFiles/analytical_piecewise.dir/build
.PHONY : analytical_piecewise/fast

#=============================================================================
# Target rules for targets named analytical_vs_numerical

# Build rule for target.
analytical_vs_numerical: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 analytical_vs_numerical
.PHONY : analytical_vs_numerical

# fast build rule for target.
analytical_vs_numerical/fast:
	$(MAKE) -f CMakeFiles/analytical_vs_numerical.dir/build.make CMakeFiles/analytical_vs_numerical.dir/build
.PHONY : analytical_vs_numerical/fast

#=============================================================================
# Target rules for targets named non_uniform_explicit_constant

# Build rule for target.
non_uniform_explicit_constant: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 non_uniform_explicit_constant
.PHONY : non_uniform_explicit_constant

# fast build rule for target.
non_uniform_explicit_constant/fast:
	$(MAKE) -f CMakeFiles/non_uniform_explicit_constant.dir/build.make CMakeFiles/non_uniform_explicit_constant.dir/build
.PHONY : non_uniform_explicit_constant/fast

#=============================================================================
# Target rules for targets named non_uniform_1D_constant

# Build rule for target.
non_uniform_1D_constant: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 non_uniform_1D_constant
.PHONY : non_uniform_1D_constant

# fast build rule for target.
non_uniform_1D_constant/fast:
	$(MAKE) -f CMakeFiles/non_uniform_1D_constant.dir/build.make CMakeFiles/non_uniform_1D_constant.dir/build
.PHONY : non_uniform_1D_constant/fast

analytical_piecewise.o: analytical_piecewise.cpp.o

.PHONY : analytical_piecewise.o

# target to build an object file
analytical_piecewise.cpp.o:
	$(MAKE) -f CMakeFiles/analytical_piecewise.dir/build.make CMakeFiles/analytical_piecewise.dir/analytical_piecewise.cpp.o
.PHONY : analytical_piecewise.cpp.o

analytical_piecewise.i: analytical_piecewise.cpp.i

.PHONY : analytical_piecewise.i

# target to preprocess a source file
analytical_piecewise.cpp.i:
	$(MAKE) -f CMakeFiles/analytical_piecewise.dir/build.make CMakeFiles/analytical_piecewise.dir/analytical_piecewise.cpp.i
.PHONY : analytical_piecewise.cpp.i

analytical_piecewise.s: analytical_piecewise.cpp.s

.PHONY : analytical_piecewise.s

# target to generate assembly for a file
analytical_piecewise.cpp.s:
	$(MAKE) -f CMakeFiles/analytical_piecewise.dir/build.make CMakeFiles/analytical_piecewise.dir/analytical_piecewise.cpp.s
.PHONY : analytical_piecewise.cpp.s

analytical_piecewise_constant_end.o: analytical_piecewise_constant_end.cpp.o

.PHONY : analytical_piecewise_constant_end.o

# target to build an object file
analytical_piecewise_constant_end.cpp.o:
	$(MAKE) -f CMakeFiles/analytical_piecewise_constant_end.dir/build.make CMakeFiles/analytical_piecewise_constant_end.dir/analytical_piecewise_constant_end.cpp.o
	$(MAKE) -f CMakeFiles/non_uniform_1D_constant.dir/build.make CMakeFiles/non_uniform_1D_constant.dir/analytical_piecewise_constant_end.cpp.o
.PHONY : analytical_piecewise_constant_end.cpp.o

analytical_piecewise_constant_end.i: analytical_piecewise_constant_end.cpp.i

.PHONY : analytical_piecewise_constant_end.i

# target to preprocess a source file
analytical_piecewise_constant_end.cpp.i:
	$(MAKE) -f CMakeFiles/analytical_piecewise_constant_end.dir/build.make CMakeFiles/analytical_piecewise_constant_end.dir/analytical_piecewise_constant_end.cpp.i
	$(MAKE) -f CMakeFiles/non_uniform_1D_constant.dir/build.make CMakeFiles/non_uniform_1D_constant.dir/analytical_piecewise_constant_end.cpp.i
.PHONY : analytical_piecewise_constant_end.cpp.i

analytical_piecewise_constant_end.s: analytical_piecewise_constant_end.cpp.s

.PHONY : analytical_piecewise_constant_end.s

# target to generate assembly for a file
analytical_piecewise_constant_end.cpp.s:
	$(MAKE) -f CMakeFiles/analytical_piecewise_constant_end.dir/build.make CMakeFiles/analytical_piecewise_constant_end.dir/analytical_piecewise_constant_end.cpp.s
	$(MAKE) -f CMakeFiles/non_uniform_1D_constant.dir/build.make CMakeFiles/non_uniform_1D_constant.dir/analytical_piecewise_constant_end.cpp.s
.PHONY : analytical_piecewise_constant_end.cpp.s

analytical_vs_numerical.o: analytical_vs_numerical.cpp.o

.PHONY : analytical_vs_numerical.o

# target to build an object file
analytical_vs_numerical.cpp.o:
	$(MAKE) -f CMakeFiles/analytical_vs_numerical.dir/build.make CMakeFiles/analytical_vs_numerical.dir/analytical_vs_numerical.cpp.o
.PHONY : analytical_vs_numerical.cpp.o

analytical_vs_numerical.i: analytical_vs_numerical.cpp.i

.PHONY : analytical_vs_numerical.i

# target to preprocess a source file
analytical_vs_numerical.cpp.i:
	$(MAKE) -f CMakeFiles/analytical_vs_numerical.dir/build.make CMakeFiles/analytical_vs_numerical.dir/analytical_vs_numerical.cpp.i
.PHONY : analytical_vs_numerical.cpp.i

analytical_vs_numerical.s: analytical_vs_numerical.cpp.s

.PHONY : analytical_vs_numerical.s

# target to generate assembly for a file
analytical_vs_numerical.cpp.s:
	$(MAKE) -f CMakeFiles/analytical_vs_numerical.dir/build.make CMakeFiles/analytical_vs_numerical.dir/analytical_vs_numerical.cpp.s
.PHONY : analytical_vs_numerical.cpp.s

non_uniform_1D_constant.o: non_uniform_1D_constant.cpp.o

.PHONY : non_uniform_1D_constant.o

# target to build an object file
non_uniform_1D_constant.cpp.o:
	$(MAKE) -f CMakeFiles/non_uniform_1D_constant.dir/build.make CMakeFiles/non_uniform_1D_constant.dir/non_uniform_1D_constant.cpp.o
.PHONY : non_uniform_1D_constant.cpp.o

non_uniform_1D_constant.i: non_uniform_1D_constant.cpp.i

.PHONY : non_uniform_1D_constant.i

# target to preprocess a source file
non_uniform_1D_constant.cpp.i:
	$(MAKE) -f CMakeFiles/non_uniform_1D_constant.dir/build.make CMakeFiles/non_uniform_1D_constant.dir/non_uniform_1D_constant.cpp.i
.PHONY : non_uniform_1D_constant.cpp.i

non_uniform_1D_constant.s: non_uniform_1D_constant.cpp.s

.PHONY : non_uniform_1D_constant.s

# target to generate assembly for a file
non_uniform_1D_constant.cpp.s:
	$(MAKE) -f CMakeFiles/non_uniform_1D_constant.dir/build.make CMakeFiles/non_uniform_1D_constant.dir/non_uniform_1D_constant.cpp.s
.PHONY : non_uniform_1D_constant.cpp.s

non_uniform_explicit_constant.o: non_uniform_explicit_constant.cpp.o

.PHONY : non_uniform_explicit_constant.o

# target to build an object file
non_uniform_explicit_constant.cpp.o:
	$(MAKE) -f CMakeFiles/non_uniform_explicit_constant.dir/build.make CMakeFiles/non_uniform_explicit_constant.dir/non_uniform_explicit_constant.cpp.o
.PHONY : non_uniform_explicit_constant.cpp.o

non_uniform_explicit_constant.i: non_uniform_explicit_constant.cpp.i

.PHONY : non_uniform_explicit_constant.i

# target to preprocess a source file
non_uniform_explicit_constant.cpp.i:
	$(MAKE) -f CMakeFiles/non_uniform_explicit_constant.dir/build.make CMakeFiles/non_uniform_explicit_constant.dir/non_uniform_explicit_constant.cpp.i
.PHONY : non_uniform_explicit_constant.cpp.i

non_uniform_explicit_constant.s: non_uniform_explicit_constant.cpp.s

.PHONY : non_uniform_explicit_constant.s

# target to generate assembly for a file
non_uniform_explicit_constant.cpp.s:
	$(MAKE) -f CMakeFiles/non_uniform_explicit_constant.dir/build.make CMakeFiles/non_uniform_explicit_constant.dir/non_uniform_explicit_constant.cpp.s
.PHONY : non_uniform_explicit_constant.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... analytical_piecewise_constant_end"
	@echo "... analytical_piecewise"
	@echo "... analytical_vs_numerical"
	@echo "... non_uniform_explicit_constant"
	@echo "... non_uniform_1D_constant"
	@echo "... analytical_piecewise.o"
	@echo "... analytical_piecewise.i"
	@echo "... analytical_piecewise.s"
	@echo "... analytical_piecewise_constant_end.o"
	@echo "... analytical_piecewise_constant_end.i"
	@echo "... analytical_piecewise_constant_end.s"
	@echo "... analytical_vs_numerical.o"
	@echo "... analytical_vs_numerical.i"
	@echo "... analytical_vs_numerical.s"
	@echo "... non_uniform_1D_constant.o"
	@echo "... non_uniform_1D_constant.i"
	@echo "... non_uniform_1D_constant.s"
	@echo "... non_uniform_explicit_constant.o"
	@echo "... non_uniform_explicit_constant.i"
	@echo "... non_uniform_explicit_constant.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

